#+MACRO: version 3.2.1
#+MACRO: kbd @@texinfo:@kbd{$1}@@

#+TITLE: Insidious Big Brother Database (BBDB) User Manual
#+AUTHOR: Christian Egli
#+EMAIL: christian.egli@sbs.ch
#+LANGUAGE: en

#+TEXINFO_FILENAME: bbdb.info
#+TEXINFO_CLASS: info
#+TEXINFO_DIR_CATEGORY: Emacs misc features
#+TEXINFO_DIR_TITLE: BBDB (bbdb)
#+TEXINFO_DIR_DESC: Insidious Big Brother Database (BBDB)

#+TEXINFO_HEADER: @syncodeindex pg cp

* Copying
  :PROPERTIES:
  :COPYING:  t
  :END:

This manual is for the Insidious Big Brother Database (BBDB) (version {{{version}}}).

Copyright @@texinfo:@copyright{}@@ 2011-2015 Roland Winkler <winkler@gnu.org>.

#+BEGIN_QUOTE
Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License,
Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, with no Front-Cover Texts,
and with no Back-Cover Texts.  A copy of the license is included in
the section entitled "GNU Free Documentation License".
#+END_QUOTE

* Introduction
BBDB, which stands for Insidious Big Brother Database is an address
book and contact management module for Emacs. BBDB can be integrated
into mail and news readers, chat clients and other modules within
Emacs. If you use BBDB to keep track of contact information, you'll be
able to look up phone numbers or notes to people's records from your
Emacs-based mail or from your org-mode documents. Even if you use bbdb
simply as as a basic address book, you'll find that BBDB's
customizability makes it surprisingly powerful.

* Installation
** Via package manager
 The easiest way to install BBDB is via the builtin package manager.
 [[http://melpa.milkbox.net/][MELPA]] contains very up-to-date packages for BBDB.

1. Add MELPA as a package archive http://melpa.org/#/getting-started
2. {{{kbd(M-x package-install @key{RET} bbdb @key{RET})}}}

** From Source
To build BBDB from source you will have to get it from
http://savannah.nongnu.org/projects/bbdb/. Check it out using git:

#+BEGIN_SRC sh
git clone git://git.savannah.nongnu.org/bbdb.git
#+END_SRC

Then build it using the usual magic incantations:

#+BEGIN_SRC sh
cd bbdb
./autogen.sh
configure
make elpa
#+END_SRC

Then inside your Emacs install the package you just built using
{{{kbd(M-x package-install-file)}}}.

For more advanced options see the =README= that comes with the source
distribution of BBDB.

* Adding contacts
When you start bbdb for the first time with {{{kbd(M-x bbdb @key{RET})}}}
you will have an empty address book. To add a contact type
{{{kbd(c)}}} in the =*BBDB*= buffer. This will prompt for a name and
several fields. You can then fill in the information or just hit
{{{kbd(@key{RET})}}} when the corresponding field is empty. When asked
for labels such as phone or address labels {{{kbd(@key{TAB})}}} will
give you a completion list of existing labels.

#+BEGIN_EXAMPLE
Alyssa P. Hacker - MIT
     address (work): 77 Massachusetts Ave
                     Cambridge, MA 02139
                     United States
               mail: alyssa.p.hacker@mit.edu
#+END_EXAMPLE

** Snarfing
* Editing records
Say you realize that you forgot to add a URL to your contact Alyssa P.
Hacker. So you go to your contact {{{kbd(M-x bbdb @key{RET} Alyssa @key{RET})}}}
and type {{{kbd(i)}}}. You will be prompted by a field name. Again
{{{kbd(@key{TAB})}}} will give you a completion list of existing
fields. Pick =url= and enter the URL. You will end up with the
following entry:

#+BEGIN_EXAMPLE
Alyssa P. Hacker - MIT
     address (work): 77 Massachusetts Ave
                     Cambridge, MA 02139
                     United States
               mail: alyssa.p.hacker@mit.edu
                url: https://mitpress.mit.edu/books/structure-and-interpretation-computer-programs
#+END_EXAMPLE


* Searching contacts
* Exporting contacts
* Integrating with mail and news readers
* Customization
* GNU Free Documentation License
  :PROPERTIES:
  :APPENDIX: t
  :END:

  #+TEXINFO: @include doclicense.texi

* Index
  :PROPERTIES:
  :INDEX:    cp
  :END:

